site_name: Coveo Challenge | Nikita Pushkarskii, 2021 ©
nav:
    - Changing Kingdom State: index.md
    - Monty API Reference: reference.md
theme: 
  name: material
plugins:
  - render_swagger
markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences